# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080
  
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "apt"
	chef.add_recipe "php"
    chef.add_recipe "apache2"
	chef.add_recipe "mysql::server"
	chef.add_recipe "wordpress"
	
	chef.json = {
	:mysql => {
    :server_root_password => "Passwort",
    :server_repl_password => "Passwort",
    :server_debian_password => "Passwort"
  }}
  end
  
end